name: Render spec

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install Tools
        run: |
          pip install pandoc-plantuml-filter
          sudo apt-get install -y pandoc plantuml
      - name: Generate Doc
        run: |
          mkdir gh-pages
          cd gh-pages
          for i in ../*.md
          do
           name=$(basename $i)
           destName="${name/\.md/.html}"
           pandoc $i -o "$destName" --filter pandoc-plantuml;
          done
          cp -r ../images/ ./
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: gh-pages
          single-commit: true
          force: true
